figure_merit='FP_INPUT.prf'
simulations=1
experiment_f='EXP_PATTERN.xye'
sample_f='FP_INPUT.pcr'
optimize='zero sycos sysin scale u y_u a b c x y z biso'
x=['Fe1','P1','O1','O2','O3']
y=['O3']
z=['Fe1','P1','O1','O2','O3']
biso=['Fe1','P1','O1','O2','O3','AL1']
